### ISSUE TITLE
Build Failure on GHC Head

### ISSUE THREAD

**Issue by nek0** [ekmett/constraints#43]
Hi there,

when building the library with GHC from the git head I encounter this error:

```
src/Data/Constraint.hs:308:7: error:
    Not in scope: type constructor or class ‘Prim.Any’
    Module ‘GHC.Prim’ does not export ‘Any’.
```

I know a similar issue was fixed some time ago, but I think this is new since GHC head changed since then. Can you please look into this? I'm not experienced with GHC internals.

**Comment by oerjan** [comment]
Hi, perhaps try using the git head of `constraints` as well; the fix doesn't seem to have made it to Hackage yet. (I guess this also means some base version constraints need to be tightened on Hackage, though.)

**Comment by bgamari** [comment]
@RyanGlScott, do you have the ability to push a new release for this?

**Comment by RyanGlScott** [comment]
@bgamari, I don't at the moment. But I wouldn't want to release `constraints` in its current HEAD state, since it [doesn't build on GHC 7.10 due to an old `Typeable` bug](https://github.com/ekmett/constraints/commit/1649e382b8dffe5e2694d0959caeba65e87a411e#commitcomment-18448388).

If I can figure out a way to work around that, I'd happily try and get a new release out. Any thoughts on how to fix that issue?

**Comment by RyanGlScott** [comment]
In particular, [here's](https://travis-ci.org/ekmett/constraints/jobs/148277997#L437) the build error you get on GHC 7.10 with the current `constraints` HEAD.

**Comment by RyanGlScott** [comment]
Ultimately, I don't think [GHC Trac #10343](https://ghc.haskell.org/trac/ghc/ticket/10343) is surmountable on GHC 7.10, so at the very least, I believe we're going to have to conditionally restrict the kinds in that `Deferrable (a ~ b)` instance to `Deferrable ((a :: *) ~ (b :: *))`.

The question is: should we also do the same for GHC 7.8? This poly-kinded `Typeable` code actually seems to work just fine on GHC 7.8, and it certainly works on GHC 8.0+. It's just GHC 7.10 that is affected. So we could either:

1. Restrict the kinds on GHC 7.10 only, and make a note of this in the Haddocks, referring to Trac #10343. This would require the least amount of changes, but there's still the unsavory aspect that we change the API on only one version of GHC.
2. Restrict the kinds on GHC 7.8 and 7.10. This would make the conditional API slightly more sensible, as then there is a minimum version of GHC you need to use poly-kinded `Deferrable` code, but it also removes a feature that used to work on GHC 7.8.

What do you `constraints` users think?

**Comment by RyanGlScott** [comment]
I've decided to go with option 1 in the [`constraints-0.9`](http://hackage.haskell.org/package/constraints-0.9) release, which I just uploaded to Hackage.
