### ISSUE TITLE
constraints-0.13.1 cannot be build with GHC 9.4

### ISSUE THREAD

**Issue by Bodigrim** [ekmett/constraints#118]
```
[5 of 7] Compiling Data.Constraint.Nat

src/Data/Constraint/Nat.hs:81:11: error:
    • Cannot satisfy: a <= b
    • In the expression: axiom
      In an equation for ‘axiomLe’: axiomLe = axiom
   |
81 | axiomLe = axiom
   |           ^^^^^

src/Data/Constraint/Nat.hs:174:10: error:
    • Cannot satisfy: 0 <= a
    • In the expression: axiom
      In an equation for ‘zeroLe’: zeroLe = axiom
    |
174 | zeroLe = axiom
    |          ^^^^^
...
```
Revision would be much appreciated.

**Comment by RyanGlScott** [comment]
I've applied a revision [here](https://hackage.haskell.org/package/constraints-0.13.1/revisions/).
