### ISSUE TITLE
Forall doesn't work as expected with multiple occurence

### ISSUE THREAD

**Issue by konn** [ekmett/constraints#7]
`Forall p` won't work as expected if there are multiple occurence of `a` in the rhs of `p a`.
A trivial example:

``` haskell
{-# LANGUAGE ConstraintKinds, LiberalTypeSynonyms, TypeOperators, TypeFamilies #-}
module Main where
import Data.Constraint
import Data.Constraint.Forall

type Reflex a = a ~ a

reflexDic :: Forall Reflex :- Reflex a
reflexDic = inst
```

This code won't compile in `constraints-0.4` plus `ghc-7.8.3`. The compilation error is as follows:

```
    Couldn't match type ‘Data.Constraint.Forall.A’
                  with ‘Data.Constraint.Forall.B’
    Expected type: Forall Reflex :- Reflex a
      Actual type: Forall ((~) Data.Constraint.Forall.A)
                   :- (Data.Constraint.Forall.A ~ a)
    In the expression: inst
    In an equation for ‘myDic’: myDic = inst
```
